import {
  Root,
  Trigger,
  Portal,
  Content,
  Item,
  Separator,
  Group,
  GroupLabel,
  Sub,
  SubTrigger,
  SubContent,
  CheckboxItem,
  ItemIndicator,
  RadioGroup,
  RadioItem,
} from "./dropdown-menu.js"

export type {
  DropdownMenuRootProps as ContextMenuRootProps,
  DropdownMenuTriggerProps as ContextMenuTriggerProps,
  DropdownMenuContentProps as ContextMenuContentProps,
  DropdownMenuItemProps as ContextMenuItemProps,
  DropdownMenuSeparatorProps as ContextMenuSeparatorProps,
  DropdownMenuSubProps as ContextMenuSubProps,
  DropdownMenuSubTriggerProps as ContextMenuSubTriggerProps,
  DropdownMenuSubContentProps as ContextMenuSubContentProps,
  DropdownMenuCheckboxItemProps as ContextMenuCheckboxItemProps,
  DropdownMenuGroupProps as ContextMenuGroupProps,
  DropdownMenuGroupLabelProps as ContextMenuGroupLabelProps,
  DropdownMenuRadioGroupProps as ContextMenuRadioGroupProps,
  DropdownMenuRadioItemProps as ContextMenuRadioItemProps,
} from "./dropdown-menu.js"

export {
  Root,
  Trigger,
  Portal,
  Content,
  Item,
  Separator,
  Group,
  GroupLabel,
  Sub,
  SubTrigger,
  SubContent,
  CheckboxItem,
  ItemIndicator,
  RadioGroup,
  RadioItem,
}

export const ContextMenu = Object.assign(Root, {
  Root,
  Trigger,
  Portal,
  Content,
  Item,
  Separator,
  Group,
  GroupLabel,
  Sub,
  SubTrigger,
  SubContent,
  CheckboxItem,
  ItemIndicator,
  RadioGroup,
  RadioItem,
})
