import { mkdirSync, rmSync, writeFileSync } from "node:fs"
import { spawnSync } from "node:child_process"
import { fileURLToPath } from "node:url"
import { join } from "node:path"
import { auditCurrentMain, ensureReactReference } from "./reference.mjs"
import { launchMailAdapter } from "./adapters.mjs"
import { compareSnapshots, snapshot, snapshotFromTree } from "./snapshot.mjs"
import { runScenarioSuite } from "./scenarios.mjs"
import { inventoryFromFile, renderInventoryMarkdown } from "./inventory.mjs"

const repoRoot = fileURLToPath(new URL("../../", import.meta.url))
const artifactRoot = join(repoRoot, "artifacts/mail-parity")
const fatalNativePattern = /cannot update .*GpuixView|already being updated|fatal runtime error|failed to initiate panic|SIGABRT|thread .* panicked/i

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: options.cwd ?? repoRoot,
    env: { ...process.env, ...options.env },
    encoding: "utf8",
    stdio: options.capture === false ? "inherit" : "pipe",
  })
  if (result.status !== 0) {
    const detail = [result.stdout, result.stderr].filter(Boolean).join("\n").trim()
    throw new Error(command + " " + args.join(" ") + " failed" + (detail ? "\n" + detail : ""))
  }
  return (result.stdout ?? "").trim()
}

function captureFatalLines(text) {
  return text
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && fatalNativePattern.test(line))
}

function markdownTable(rows) {
  return [
    "| Scenario | React | Solid | Comparison |",
    "| --- | --- | --- | --- |",
    ...rows.map((row) => "| " + row.id + " | " + row.react + " | " + row.solid + " | " + row.comparison + " |"),
  ].join("\n")
}

function writeReport({ startSha, react, currentMain, inventory, runs, comparisons, fatalLines }) {
  const report = [
    "# React and Solid Mail parity",
    "",
    "This report is generated by scripts/mail-parity/run.mjs. It uses the same live-native scenario definitions against the upstream React app and the Solid app.",
    "",
    "## Exact inputs",
    "",
    "- Solid repository start SHA: " + startSha,
    "- React GPUIX checkout SHA: " + react.sha,
    "- React package version: " + react.packageVersion,
    "- React Mail source blob: " + react.mailBlobSha,
    "- Current Solid test SHA: " + run("git", ["rev-parse", "HEAD"]),
    "- Current upstream main audit SHA: " + (currentMain?.currentSha ?? "not run"),
    "",
    "## Commands",
    "",
    "    bun install --frozen-lockfile",
    "    bun run build",
    "    bun run mail:parity",
    "",
    "The suite builds and launches two live native processes with GPUIX stdio automation. It does not call application state setters or use TestRenderer.",
    "",
    "## Shared scenario result",
    "",
    markdownTable(
      runs.map((row) => ({
        id: row.id,
        react: row.react ? "passed" : "failed",
        solid: row.solid ? "passed" : "failed",
        comparison: comparisons[row.id]?.length ? comparisons[row.id].join("; ") : "matched",
      })),
    ),
    "",
    "## Crash and process evidence",
    "",
    "- Fatal native signature lines: " + fatalLines.length,
    fatalLines.length ? fatalLines.map((line) => "    " + line).join("\n") : "No configured fatal native signatures were observed.",
    "",
    renderInventoryMarkdown(inventory),
    "",
    "## Future upstream-main parity",
    "",
    currentMain
      ? "The exact 0.8.0 Mail source was compared with upstream main at " +
        currentMain.currentSha +
        ". The raw diff is stored below for follow-up review; it is not mixed into the release parity result."
      : "The current-main audit did not run because the exact 0.8.0 parity suite did not finish green.",
    "",
    currentMain
      ? currentMain.diff.trim()
        ? "    " + currentMain.diff.replace(/\n/g, "\n    ")
        : "No changes to examples/mail.tsx were found between the exact 0.8.0 reference and upstream main."
      : "",
    "",
    "## Known intentional differences and limits",
    "",
    "- React and Solid use different framework runtimes, but the scenario compares visible semantics rather than framework internals.",
    "- Native text metrics and platform rasterization are not expected to be pixel-identical. Important bounds use an 8 px tolerance.",
    "- The upstream Mail source leaves several IconButton surfaces inert. The shared inert-icon scenario records that clicking them does not change semantic state.",
    "- The Solid stdio automation backend does not currently expose getScrollOffset. React offsets are recorded where its API exposes them; scroll-offset equality is skipped when Solid cannot report the value.",
    "- The automation tree does not expose every CSS-computed style or reliable native image-load completion state, so this report compares image presence, bounds, and visible text.",
    "",
    "## Artifact locations",
    "",
    "- React screenshots: artifacts/mail-parity/react/",
    "- Solid screenshots: artifacts/mail-parity/solid/",
    "- Semantic snapshots: artifacts/mail-parity/react/snapshots.json and artifacts/mail-parity/solid/snapshots.json",
    "- Native stderr logs: artifacts/mail-parity/react/stderr.log and artifacts/mail-parity/solid/stderr.log",
    "- This report: artifacts/mail-parity/report.md",
    "",
  ].join("\n")
  writeFileSync(join(artifactRoot, "report.md"), report)
}

const startSha = run("git", ["rev-parse", "HEAD"])
run("bun", ["run", "build"], { capture: false })
rmSync(artifactRoot, { recursive: true, force: true })
mkdirSync(join(artifactRoot, "react"), { recursive: true })
mkdirSync(join(artifactRoot, "solid"), { recursive: true })

const react = ensureReactReference(repoRoot)
const outcomes = {}
const snapshots = { react: [], solid: [] }
const fatalLines = []

for (const kind of ["react", "solid"]) {
  const adapter = await launchMailAdapter(kind, repoRoot, react)
  adapter.snapshotNow = (label) => snapshot(adapter, label)
  adapter.snapshot = (root) => snapshotFromTree(adapter, root, "inert-state")
  try {
    const context = await runScenarioSuite(adapter, join(artifactRoot, kind))
    outcomes[kind] = { passed: true, results: context.results }
    snapshots[kind] = context.snapshots
  } catch (error) {
    outcomes[kind] = { passed: false, error: error instanceof Error ? error.message : String(error) }
  } finally {
    fatalLines.push(
      ...captureFatalLines(adapter.stderr() + "\n" + adapter.stdout()).map((line) => kind + ": " + line),
    )
    const exit = adapter.exitResult()
    if (exit) {
      outcomes[kind] = {
        passed: false,
        error: "process exited (code=" + String(exit.code) + ", signal=" + String(exit.signal) + ")",
      }
    }
    writeFileSync(join(artifactRoot, kind, "stderr.log"), adapter.stderr())
    writeFileSync(
      join(artifactRoot, kind, "snapshots.json"),
      JSON.stringify(snapshots[kind], null, 2) + "\n",
    )
    await adapter.close()
  }
}

const comparisons = {}
const reactByLabel = new Map(snapshots.react.map((item) => [item.label, item]))
const solidByLabel = new Map(snapshots.solid.map((item) => [item.label, item]))
for (const [label, reactSnapshot] of reactByLabel) {
  const solidSnapshot = solidByLabel.get(label)
  if (!solidSnapshot) {
    comparisons[label] = ["missing Solid checkpoint"]
    continue
  }
  comparisons[label] = compareSnapshots(reactSnapshot, solidSnapshot)
}

const runIds = [...new Set([
  ...(outcomes.react?.results ?? []).map((item) => item.id),
  ...(outcomes.solid?.results ?? []).map((item) => item.id),
])]
const runs = runIds.map((id) => ({
  id,
  react: Boolean(outcomes.react?.passed && outcomes.react.results.some((item) => item.id === id)),
  solid: Boolean(outcomes.solid?.passed && outcomes.solid.results.some((item) => item.id === id)),
}))
const parityGreen =
  Boolean(outcomes.react?.passed) &&
  Boolean(outcomes.solid?.passed) &&
  Object.values(comparisons).every((items) => items.length === 0)
const currentMain = parityGreen ? auditCurrentMain(react.checkout) : null
const inventory = inventoryFromFile(join(react.checkout, "examples/mail.tsx"))
writeReport({ startSha, react, currentMain, inventory, runs, comparisons, fatalLines })

if (!parityGreen) {
  console.error("Mail React/Solid parity failed.")
  if (outcomes.react?.error) console.error("React: " + outcomes.react.error)
  if (outcomes.solid?.error) console.error("Solid: " + outcomes.solid.error)
  for (const [label, items] of Object.entries(comparisons)) {
    if (items.length) console.error(label + ": " + items.join("; "))
  }
  process.exitCode = 1
} else {
  console.log("Mail React/Solid live-native parity passed.")
  console.log("React SHA: " + react.sha)
  console.log("React Mail blob: " + react.mailBlobSha)
  console.log("Current upstream main: " + currentMain.currentSha)
  console.log("Screenshots and report: " + artifactRoot)
}
