export const TIMELINE_SIDEBAR_MIN_WIDTH = 336

export const TIMELINE_LEFT_BROWSER_MIN_WIDTH = 220
export const TIMELINE_LEFT_BROWSER_DEFAULT_WIDTH = 280
export const TIMELINE_LEFT_BROWSER_MAX_WIDTH_RATIO = 0.42
export const TIMELINE_LEFT_BROWSER_MIN_TIMELINE_WIDTH = 360
